# Generated by Django 4.0.2 on 2022-11-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
