# Generated by Django 4.0.2 on 2022-11-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0008_alter_cart_user_cartitem_alter_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='product_api.CartItem'),
        ),
    ]
