# Generated by Django 4.0.2 on 2022-11-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0010_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='product_api.CartItem'),
        ),
    ]
