# Generated by Django 4.0.2 on 2022-11-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0011_alter_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
