# Generated by Django 4.0.2 on 2022-12-01 11:28

from django.db import migrations, models
import product_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0013_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=product_api.models.upload_location),
        ),
    ]
