# Generated by Django 4.0.2 on 2022-11-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='special_user',
        ),
    ]
