# Generated by Django 4.0.2 on 2022-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_remove_siteuser_special_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='special_user',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('super-admin', 'super-admin')], default='user', max_length=20),
        ),
    ]
